<?php
use Drupal\Core\Routing\RouteMatchInterface;

function geonorge_mosaic_help($route_name, RouteMatchInterface $route_match)
{
    switch ($route_name) {
    // Main module help for the metsis_search module.
    /** TODO: Read help from module's README.md */
    case 'help.page.geonorge_mosaic':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Geonorge Sentinel-2 Mosaic') . '</p>';
      return $output;

    default:
  }
}


// Implements hook_theme()
function geonorge_mosaic_theme( $existing, $type, $theme, $path ){
    return [
        'geonorge_mosaic-template' => [
            'render element' => 'container', // To render a simple container element
            'template' => 'geonorge_mosaic', // My template file name
            'variables' => [
              'helptext' => '',
            ]

        ],
    ];
}
