geonorge_mosaic.settings:
  type: config_object
  label: 'Geonorge mosaic configuration'
  mapping:
    helptext:
      label: 'Infotext to be desplayed above the map'
      type: text_format
    lancode:
      type: string
      label: 'Language code'
    lat:
      type: int
      label: 'Initial centre latitude for map'
    lon:
      type: int
      label: 'Initial centre longitude for map'
    zoom_level:
      type: int
      label: 'Initial zoom level for map'
